include delphi.inc

all: Test1.exe Test2.exe Test3.exe

clean: clean-prog

clean-prog:
	rm -f Test1.exe Test2.exe Test3.exe

Test1.exe: Test1.dpr

Test2.exe: Test2.dpr

Test3.exe: Test3.dpr Test3.mo



