#$Id: Makefile,v 1.3 2001/02/16 00:56:05 juanco Exp $
ROOT=..\..

include $(ROOT)\Rules.mak

all: 
	$(DCC) -B Step1\RegistryTest.dpr
	$(DCC) -B Step2\RegistryTest.dpr
	$(DCC) -B Step3\RegistryTest.dpr

